// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  Auth: {
    Cognito: {
      identityPoolId: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID,
      allowGuestAccess: true,
    },
  },
  API: {
    GraphQL: {
      endpoint: process.env.NEXT_PUBLIC_ENDPOINT,
      region: process.env.NEXT_PUBLIC_REGION,
      defaultAuthMode: process.env.NEXT_PUBLIC_DEFAULT_AUTH_MODE,
    },
  },
};

export default config;
