// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://zg4touiaavathhefbjzkouvlay.appsync-api.ap-northeast-1.amazonaws.com/graphql",
      region: "ap-northeast-1",
      defaultAuthMode: "iam",
    },
  },
};

export default config;
